<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-C0K6CVK" failures="4" tests="11" name="Default test" time="65.398" errors="0" timestamp="2023-04-08T11:51:57 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="7.328"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.437"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.5"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.227"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.394">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at stepdefinitions.LoginTest.user_should_get_a_proper_warning_message(LoginTest.java:59)
at ✽.user should get a proper warning message(file:///C:/OpenCart-Selenium-Cucumber-POM/src/test/resources/featurefiles/login.feature:16)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.256">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at stepdefinitions.LoginTest.user_should_get_a_proper_warning_message(LoginTest.java:59)
at ✽.user should get a proper warning message(file:///C:/OpenCart-Selenium-Cucumber-POM/src/test/resources/featurefiles/login.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.036">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at stepdefinitions.LoginTest.user_should_get_a_proper_warning_message(LoginTest.java:59)
at ✽.user should get a proper warning message(file:///C:/OpenCart-Selenium-Cucumber-POM/src/test/resources/featurefiles/login.feature:30)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.837">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at stepdefinitions.LoginTest.user_should_get_a_proper_warning_message(LoginTest.java:59)
at ✽.user should get a proper warning message(file:///C:/OpenCart-Selenium-Cucumber-POM/src/test/resources/featurefiles/login.feature:37)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.37"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.434"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.895"/>
</testsuite> <!-- Default test -->
